Repository incubateindia/Hacktoberfest, pull requests merged in 2019-10, with the labels that each got.

#1 I added Readme
  hiteshsubnani/README.md
Labels: Hacktoberfest

#2 apple created
  kroy96/apple.md
Labels: Hacktoberfest

#3 hello!
  hiteshsubnani/README.md
Labels: Eligible, Hacktoberfest

#17 Added my email id
  satyam/README.md
Labels: Bonus, Eligible, Hacktoberfest

#16 added my details
  inderjeet/README.md
Labels: Bonus, Eligible, Hacktoberfest

#13 Added my Details
  README.md
  RishabMangal/README.md
  hiteshsubnani/README.md
  kroy96/apple.md
Labels: Hacktoberfest

#10 Edit my details
  bhavanshujain/README.md
Labels: Bonus, Eligible, Hacktoberfest

#31 hey! m here
  yash chauhan/README.md
Labels: Bonus, Eligible, Hacktoberfest

#6 Create README.md
  Pranjalpatel1/README.md
Labels: Bonus, Eligible, Hacktoberfest

#32 README.md created
  Mohit/README.md
Labels: Bonus, Eligible, Hacktoberfest

#29 Added details for Saurav
  Saurav/README.txt
Labels: Bonus, Eligible, Hacktoberfest

#28 Jay Joshi All details pull request
  Jay/README.md
Labels: Bonus, Eligible, Hacktoberfest

#12 Pranav's commit
  pranavsindura/README.md
Labels: Bonus, Eligible, Hacktoberfest

#11 Added my details
  hardik/README.md
Labels: Bonus, Eligible, Hacktoberfest

#5 hacktober:add email
  Dhwajsharma/README.md
Labels: Bonus, Eligible, Hacktoberfest

#33 Create ball1.md
  sahilsoni/ball1.md
Labels: Bonus, Eligible, Hacktoberfest

#4 hacktoberfest: add Readme
  chityanj/README.MD
Labels: Bonus, Eligible, Hacktoberfest

#34 Updated My Read me filing Repo
  README.md
Labels: Bonus, Eligible, Hacktoberfest, enhancement

#38 Update Files and correct my mistake.
  Tokir/README.md
Labels: Eligible, Hacktoberfest

#37 Added my name and email
  pranjal1127/README.md
Labels: Bonus, Eligible, Hacktoberfest

#51 pull request 1
  HarshalShrimali/add
  HarshalShrimali/hackerrankques.txt
Labels: Eligible

#50 Added name
  shubham/README.md
Labels: Eligible

#49 yo
  Dhwajsharma/README.md
  Jay/README.md
  Mohit/README.md
  NakshatraSaxena/README.md
  Tokir/README.md
  sahilsoni/ball1.md
  satyam/README.md
  yash chauhan/README.md
Labels: Eligible

#43 Update README.MD
  chityanj/README.MD
Labels: Eligible

#41 Add Ayush Rawal
  Ayush/README.md
Labels: Bonus, Eligible, Hacktoberfest

#40 add readme
  Sharma/yourname/README.md
Labels: Eligible
